Update f1winstall

diff --git a/f1winstall b/f1winstall
--- a/f1winstall
+++ b/f1winstall
@@ -25,16 +25,9 @@ TARGET_SGDISK="$(pwd)/sgdisk"
 # Check the device codename using getprop
 DEVICE_CODENAME=$(getprop ro.product.device)
 
-if [ "$DEVICE_CODENAME" = "nabu" ]; then
+elif [ "$DEVICE_CODENAME" = "beryllium" ]; then
     echo ""
-    echo "WinInstaller for Xiaomi Pad 5 ($DEVICE_CODENAME)"
-    echo "this script is Written and Made By ArKT, Telegram - '@ArKT_7', Github - 'ArKT-7'"
-    echo ""
-    echo "Based on Kumar_Jy's Wininstaller, Telegram - '@Kumar_Jy', Github - 'Kumar-Jy'"
-    echo ""
-elif [ "$DEVICE_CODENAME" = "dm3q" ]; then
-    echo "test for other device"
-    echo "WinInstaller for Samsung S23 Ultra ($DEVICE_CODENAME)"
+    echo "WinInstaller for Poco F1 ($DEVICE_CODENAME)"
     echo "this script is Written and Made By ArKT, Telegram - '@ArKT_7', Github - 'ArKT-7'"
     echo ""
     echo "Based on Kumar_Jy's Wininstaller, Telegram - '@Kumar_Jy', Github - 'Kumar-Jy'"
@@ -87,8 +80,8 @@ TARGET_FILE1="$(pwd)/Toolbox.zip"
 URL2="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/userdata.img"
 TARGET_FILE2="$(pwd)/userdata.img"
 
-URL3="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/metadata.img"
-TARGET_FILE3="$(pwd)/metadata.img"
+# URL3="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/metadata.img"
+# TARGET_FILE3="$(pwd)/metadata.img"
 
 # Download the Toolbox.zip file
 echo "Downloading additional Windows tools file (Toolbox.zip), office, activator, and other things"
@@ -115,16 +108,16 @@ else
 fi
 
 # Download the metadata.img file
-echo "Downloading metadata.img"
-$(pwd)/busybox wget -O "$TARGET_FILE3" "$URL3"
+# echo "Downloading metadata.img"
+# $(pwd)/busybox wget -O "$TARGET_FILE3" "$URL3"
 
 # Check if the download was successful
-if [ $? -eq 0 ]; then
-    echo "Download complete for metadata.img."
-else
-    echo "Failed to download $URL3."
-    exit 1
-fi
+# if [ $? -eq 0 ]; then
+    # echo "Download complete for metadata.img."
+# else
+    # echo "Failed to download $URL3."
+    # exit 1
+# fi
 
 echo "All downloads completed."
 echo ""
