Update nabuwimlib

diff --git a/nabuwimlib b/nabuwimlib
--- a/nabuwimlib
+++ b/nabuwimlib
@@ -100,6 +100,9 @@ TARGET_FILE4="$(pwd)/install.bat"
 URL5="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/pe/sta.exe"
 TARGET_FILE5="$(pwd)/sta.exe"
 
+URL6="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/woa_helper.apk"
+TARGET_FILE6="$(pwd)/woa_helper.apk"
+
 # Download the Toolbox.zip file
 echo "Downloading additional Windows tools file (Toolbox.zip), office, activator, and other things"
 $(pwd)/busybox wget -O "$TARGET_FILE1" "$URL1"
@@ -124,18 +127,6 @@ else
     exit 1
 fi
 
-# Download the install.bat file
-echo "Downloading install.bat"
-$(pwd)/busybox wget -O "$TARGET_FILE4" "$URL4"
-
-# Check if the download was successful
-if [ $? -eq 0 ]; then
-    echo "Download complete for install.bat."
-else
-    echo "Failed to download $URL4."
-    exit 1
-fi
-
 # Download the metadata.img file
 # echo "Downloading metadata.img"
 # $(pwd)/busybox wget -O "$TARGET_FILE3" "$URL3"
@@ -148,6 +139,18 @@ fi
     # exit 1
 # fi
 
+# Download the install.bat file
+echo "Downloading install.bat"
+$(pwd)/busybox wget -O "$TARGET_FILE4" "$URL4"
+
+# Check if the download was successful
+if [ $? -eq 0 ]; then
+    echo "Download complete for install.bat."
+else
+    echo "Failed to download $URL4."
+    exit 1
+fi
+
 # Download the sta.exe file
 echo "Downloading sta.exe"
 $(pwd)/busybox wget -O "$TARGET_FILE5" "$URL5"
@@ -157,6 +160,18 @@ if [ $? -eq 0 ]; then
     echo "Download complete for sta.exe"
 else
     echo "Failed to download $URL5."
+    exit 1
+fi
+
+# Download the woa_helper.apk file
+echo "Downloading woa_helper.apk"
+$(pwd)/busybox wget -O "$TARGET_FILE6" "$URL6"
+
+# Check if the download was successful
+if [ $? -eq 0 ]; then
+    echo "Download complete for woa_helper.apk"
+else
+    echo "Failed to download $URL6."
     exit 1
 fi
 
@@ -582,9 +597,8 @@ fi
 # Mount partitions
 echo ""
 echo "Mounting partitions..."
-$(pwd)/busybox mkdir -p /mnt/{win,esp}
+$(pwd)/busybox mkdir -p /mnt/win
 $(pwd)/mount.ntfs /dev/block/by-name/win /mnt/win
-$(pwd)/busybox mount /dev/block/by-name/esp /mnt/esp
 
  copy_with_progress() {
     local src_file=$1
@@ -616,9 +630,11 @@ echo "Copying files..."
 $(pwd)/busybox mkdir -p /mnt/win/installer/Driver
 $(pwd)/busybox mkdir -p /mnt/win/importantbackups
 copy_with_progress /sdcard/nopcwinstall/uefi.img /sdcard/UEFI/uefi.img
+copy_with_progress /sdcard/nopcwinstall/install.bat /mnt/win/installer/install.bat
+$(pwd)/busybox cp /sdcard/nopcwinstall/sta.exe /mnt/win/installer/sta.exe
+copy_with_progress /sdcard/importantbackups/boot.img /mnt/win/boot.img
 copy_with_progress $(pwd)/install.bat /mnt/win/installer/install.bat
 copy_with_progress $(pwd)/sta.exe /mnt/win/installer/sta.exe
-copy_with_progress /sdcard/importantbackups/boot.img /mnt/win/boot.img
 echo "Copying Important .img Backup files just in case if needed further..."
 $(pwd)/busybox cp -r /sdcard/importantbackups/* /mnt/win/importantbackups/
 
@@ -640,7 +656,9 @@ echo ""
 echo "Writing winpe image to the device..."
 $(pwd)/busybox dd if=/sdcard/nopcwinstall/pe.img of=/dev/block/by-name/esp bs=64M
 $(pwd)/busybox dd if=/sdcard/nopcwinstall/uefi.img of=/dev/block/by-name/boot$(getprop ro.boot.slot_suffix) bs=8M
-
+echo ""
+echo "installing latest WOA HELPER APP for dualboot to Windows"
+pm install $(pwd)/woa_helper.apk
 # Clean up
 echo ""
 echo "Cleaning up..."
