Update nopcwinstall

diff --git a/nopcwinstall b/nopcwinstall
--- a/nopcwinstall
+++ b/nopcwinstall
@@ -74,25 +74,43 @@ echo "All binaries have been downloaded and permissions set."
 echo "meowwww"
 echo ""
 
-#!/bin/sh
+
+
+
 
 # Define the URL and target file path
 URL="https://raw.githubusercontent.com/arkt-7/won-deployer/main/files/Toolbox.zip"
 TARGET_FILE="/data/local/tmp/Toolbox.zip"
 
-# Download the file
-echo "Downloading Additional file"
-
-# Use wget with options to suppress unwanted output
-/data/local/tmp/busybox wget -q --show-progress -O "$TARGET_FILE" "$URL"
-
-# Check if the download was successful
-if [ $? -eq 0 ]; then
-    echo "Download complete."
+# Check if curl is available
+if command -v curl > /dev/null; then
+    # Download the file using curl with progress bar
+    echo "Downloading $URL to $TARGET_FILE..."
+    curl -L -o "$TARGET_FILE" "$URL"
+    
+    # Check if the download was successful
+    if [ $? -eq 0 ]; then
+        echo "Download complete."
+    else
+        echo "Failed to download $URL."
+        exit 1
+    fi
 else
-    echo "Failed to download $URL."
-    exit 1
+    echo "curl is not available. Downloading using busybox wget..."
+    # Download the file using busybox wget (default output)
+    /data/local/tmp/busybox wget -q -O "$TARGET_FILE" "$URL"
+    
+    # Check if the download was successful
+    if [ $? -eq 0 ]; then
+        echo "Download complete."
+    else
+        echo "Failed to download $URL."
+        exit 1
+    fi
 fi
+
+
+
 
 
 if [ "$DEVICE_CODENAME" = "nabu" ]; then
