Update nopcwinstall

diff --git a/nopcwinstall b/nopcwinstall
--- a/nopcwinstall
+++ b/nopcwinstall
@@ -76,30 +76,6 @@ echo ""
 
 
 
-
-#!/bin/sh
-
-# Define the URL and target file path
-URL="https://raw.githubusercontent.com/arkt-7/won-deployer/main/files/Toolbox.zip"
-TARGET_FILE="/data/local/tmp/Toolbox.zip"
-
-# Download the file
-echo "Downloading Addition windows file, office, activater and other things"
-/data/local/tmp/busybox wget -O "$TARGET_FILE" "$URL"
-
-# Check if the download was successful
-if [ $? -eq 0 ]; then
-    echo "Download complete."
-else
-    echo "Failed to download $URL."
-    exit 1
-fi
-
-
-
-
-
-
 if [ "$DEVICE_CODENAME" = "nabu" ]; then
     echo ""
     echo "WinInstaller for Xiaomi Pad 5 ($DEVICE_CODENAME)"
@@ -274,6 +250,32 @@ for file in "${EXPECTED_FILES[@]}"; do
         exit 1
     fi
 done
+
+
+
+
+
+# Define the URL and target file path
+URL="https://raw.githubusercontent.com/arkt-7/won-deployer/main/files/Toolbox.zip"
+TARGET_FILE="/data/local/tmp/Toolbox.zip"
+
+# Download the file
+echo "Downloading Addition windows file, office, activater and other things"
+/data/local/tmp/busybox wget -O "$TARGET_FILE" "$URL"
+
+# Check if the download was successful
+if [ $? -eq 0 ]; then
+    echo "Download complete."
+else
+    echo "Failed to download $URL."
+    exit 1
+fi
+
+
+
+
+
+
 
 # List and select Windows files
 echo ""
