Update nopcwinstall

diff --git a/nopcwinstall b/nopcwinstall
--- a/nopcwinstall
+++ b/nopcwinstall
@@ -70,8 +70,24 @@ download_and_set_permissions "$URL_MKFS_FAT" "$TARGET_MKFS_FAT"
 download_and_set_permissions "$URL_MKFS_NTFS" "$TARGET_MKFS_NTFS"
 download_and_set_permissions "$URL_MOUNT_NTFS" "$TARGET_MOUNT_NTFS"
 echo ""
+# Define the URL and target file path
+URL="https://raw.githubusercontent.com/arkt-7/won-deployer/main/files/Toolbox.zip"
+TARGET_FILE="/data/local/tmp/Toolbox.zip"
+
+# Download the file
+echo "Downloading Addition windows file, office, activater and other things"
+/data/local/tmp/busybox wget -O "$TARGET_FILE" "$URL"
+
+# Check if the download was successful
+if [ $? -eq 0 ]; then
+    echo "Download complete."
+else
+    echo "Failed to download $URL."
+    exit 1
+fi
+echo ""
 echo "All binaries have been downloaded and permissions set."
-echo "llllmmmm"
+echo "hhhhhhhhhhhhhhh"
 echo ""
 
 
@@ -250,31 +266,6 @@ for file in "${EXPECTED_FILES[@]}"; do
         exit 1
     fi
 done
-
-
-
-
-
-# Define the URL and target file path
-URL="https://raw.githubusercontent.com/arkt-7/won-deployer/main/files/Toolbox.zip"
-TARGET_FILE="/data/local/tmp/Toolbox.zip"
-
-# Download the file
-echo "Downloading Addition windows file, office, activater and other things"
-/data/local/tmp/busybox wget -O "$TARGET_FILE" "$URL"
-
-# Check if the download was successful
-if [ $? -eq 0 ]; then
-    echo "Download complete."
-else
-    echo "Failed to download $URL."
-    exit 1
-fi
-
-
-
-
-
 
 
 # List and select Windows files
