Update nopcwinstall

diff --git a/nopcwinstall b/nopcwinstall
--- a/nopcwinstall
+++ b/nopcwinstall
@@ -200,21 +200,25 @@ repartition_windows() {
             echo "backuping persist.img..."
             $(pwd)/busybox dd if=/dev/block/bootdevice/by-name/persist of=$(pwd)/persist.img 2>&1 | grep 'bytes'
             if [[ -n $size_win ]]; then
-                winmax=$(echo "($max - 10872 - 700 - 100)/1000" | bc)
-                echo "Min size is 20, max size is less than $winmax"
-                if ! [[ $size_win =~ ^[0-9]{1,3}(\.[0-9])?$ && $(echo "20 < $size_win && $size_win < $winmax" | bc) == 1 ]]; then
-                    echo "Invalid argument!"
+                winmax=$(echo "($max - 10872 - 635 - 100)/1000" | bc)
+                echo "Min size is 30, max size is less than $winmax GB"
+                if ! [[ $size_win =~ ^[0-9]{1,3}(\.[0-9])?$ && $(echo "30 < $size_win && $size_win < $winmax" | bc) == 1 ]]; then
+                    echo "Invalid argument! please give corrent size accordingly"
                     exit 1
                 fi
-                echo "$(echo "scale=2; $size_win*1000/1024" | bc) GiB of space will be given to the main Windows partition"
-                userdataend=$(echo "$max - $size_win*1000 - 700" | bc)
-                echo "userdata will get $(echo "scale=2; ($userdataend-10872)/1024" | bc) GiB of space"
+                echo ""
+                echo "Windows will get $(echo "scale=2; $size_win*1000/1024" | bc) GB of space"
+                echo ""
+                userdataend=$(echo "$max - $size_win*1000 - 635" | bc)
+                echo "Android will get $(echo "scale=2; ($userdataend-10872)/1024" | bc) GB of space"
+                echo ""
                 echo -n "Does that sound good? (y/n) "
                 read yn
-                [[ $yn =~ ^[Yy].*$ ]] || { echo "Rethink things carefully, and eventually, you'll come to a conclusion."; exit 1; }
+                echo ""
+                [[ $yn =~ ^[Yy].*$ ]] || { echo "Rethink things carefully about the size and then re-run this script."; echo ""; exit 1; }
             fi
 
-            winend=$((max-700))"MB"
+            winend=$((max-635))"MB"
             removeparts
             $(pwd)/sgdisk --resize-table 64 /dev/block/sda
             $(pwd)/parted -s /dev/block/sda \
