Update panelchk

diff --git a/panelchk b/panelchk
--- a/panelchk
+++ b/panelchk
@@ -268,6 +268,54 @@ echo "Size of Windows Partition: $size_win_gb GB"
 echo "Size of ESP Partition: $size_esp_mb MB"
 echo "Size of Android partition: $size_userdata_gb GB"
 
+# Continue with other operations if checks pass
+echo "Partition sizes are sufficient. Proceeding with the rest of the script..."
+
+# Define directories
+MAIN_DIR="/sdcard/"
+DIR_UNZIP="/sdcard/nopcwinstall/"
+DIR_BACK="/sdcard/backups/"
+DIR_UEFI="/sdcard/UEFI/"
+
+# Function to check and create directories
+check_and_create_dir() {
+    local dir=$1
+    if [ -d "$dir" ]; then
+        # echo "Directory $dir exists. Removing it."
+        $(pwd)/busybox rm -rf "$dir"
+    fi
+    # echo "Creating directory: $dir"
+    $(pwd)/busybox mkdir -p "$dir"
+}
+
+# Check and create directories
+check_and_create_dir "$DIR_UNZIP"
+check_and_create_dir "$DIR_BACK"
+check_and_create_dir "$DIR_UEFI"
+echo ""
+
+# Backup current partitions
+echo "Backing up Important partitions..."
+echo ""
+
+echo "Backing up boot.img..."
+dd if=/dev/block/platform/soc/1d84000.ufshc/by-name/boot$(getprop ro.boot.slot_suffix) of=/sdcard/backups/boot.img 2>&1 | grep 'bytes'
+
+echo "Backing up dtbo.img..."
+dd if=/dev/block/platform/soc/1d84000.ufshc/by-name/dtbo$(getprop ro.boot.slot_suffix) of=/sdcard/backups/dtbo.img 2>&1 | grep 'bytes'
+
+for part in fsc fsg modemst1 modemst2; do
+  echo "Backing up $part.img..."
+  dd if=/dev/block/by-name/$part of=/sdcard/backups/$part.img 2>&1 | grep 'bytes'
+done
+
+
+echo ""
+echo ""
+echo "Size of Windows Partition: $size_win_gb GB"
+echo "Size of ESP Partition: $size_esp_mb MB"
+echo "Size of Android partition: $size_userdata_gb GB"
+
 # List and select ZIP files
 echo ""
 echo "Searching for ZIP files..."
@@ -304,7 +352,7 @@ echo "Unzipping selected file..."
 $(pwd)/busybox unzip "$SELECTED_ZIP_FILE" -d "$DIR_UNZIP"
 
 # Check for specific files
-EXPECTED_FILES=("Driver.zip" "uefi.img" "install.bat" "pe" "install.esd" "ebbg" "tianma" "newebbg.img" "newtianma.img")
+EXPECTED_FILES=("Driver.zip" "uefi.img" "install.bat" "pe")
 
 for file in "${EXPECTED_FILES[@]}"; do
     if [ ! -f "$DIR_UNZIP/$file" ]; then
@@ -315,12 +363,54 @@ for file in "${EXPECTED_FILES[@]}"; do
 done
 
 
+# List and select Windows files
+echo ""
+echo "Searching for Windows files..."
+echo ""
+esd_files=($( $(pwd)/busybox find "$MAIN_DIR" -type f -name "*.esd" ))
+
+# Check if no ESD files were found
+if [ ${#esd_files[@]} -eq 0 ]; then
+    echo "No Windows files found. Please download and place an ESD file in the directory."
+    exit 1
+fi
+
+# If only one ESD file is found, automatically select it
+if [ ${#esd_files[@]} -eq 1 ]; then
+    SELECTED_ESD_FILE="${esd_files[0]}"
+    echo "ESD file found: $(basename "$SELECTED_ESD_FILE")"
+    echo "Automatically selecting this file."
+else
+    # If more than one ESD file is found, prompt user for selection
+    echo "Available Windows files:"
+    count=1
+    for file in "${esd_files[@]}"; do
+        echo "$count. $(basename "$file")"
+        files[$count]=$file
+        count=$((count + 1))
+    done
+
+    echo ""
+    echo "Enter the serial number of the Windows file to select:"
+    read selection
+
+    # Validate Windows file selection
+    if [ -z "${files[$selection]}" ]; then
+        echo "Invalid selection. Exiting."
+        exit 1
+    fi
+
+    SELECTED_ESD_FILE="${files[$selection]}"
+fi
+echo ""
+echo "Selected Windows file: $(basename "$SELECTED_ESD_FILE")"
+
 # Unmount and format partitions
 echo ""
 echo "Unmounting and formatting partitions..."
 $(pwd)/busybox umount /dev/block/by-name/{esp,win}
-$(pwd)/mkfs.fat -F32 -s1 /dev/block/by-name/esp -n ESPF1
-$(pwd)/mkfs.ntfs -f /dev/block/by-name/win -L WINF1
+$(pwd)/mkfs.fat -F32 -s1 /dev/block/by-name/esp -n ESPNABU
+$(pwd)/mkfs.ntfs -f /dev/block/by-name/win -L WINNABU
 
 # Mount partitions
 echo ""
@@ -357,15 +447,11 @@ $(pwd)/busybox mount /dev/block/by-name/esp /mnt/esp
 echo ""
 echo "Copying files..."
 $(pwd)/busybox mkdir -p /mnt/win/installer/Driver
-$(pwd)/busybox mkdir -p /mnt/win/importantbackups
-
-
+copy_with_progress /sdcard/nopcwinstall/uefi.img /sdcard/UEFI/uefi.img
 copy_with_progress /sdcard/nopcwinstall/install.bat /mnt/win/installer/install.bat
 copy_with_progress /sdcard/nopcwinstall/rmdir.bat /mnt/win/rmdir.bat
-copy_with_progress /sdcard/importantbackups/boot.img /mnt/win/boot.img
-echo "Copying Important .img Backup files just in case if needed further..."
-$(pwd)/busybox cp -r /sdcard/importantbackups/* /mnt/win/importantbackups/
-copy_with_progress /sdcard/nopcwinstall/install.esd /mnt/win/installer/install.esd
+copy_with_progress /sdcard/backups/boot.img /mnt/win/boot.img
+copy_with_progress "$SELECTED_ESD_FILE" /mnt/win/installer/install.esd
 
 # Unzip Toolbox.zip
 echo ""
