Update test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -9,6 +9,8 @@ URL_MKFS_NTFS="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/mk
 URL_MOUNT_NTFS="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/mount.ntfs"
 URL_PARTED="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/parted"
 URL_SGDISK="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/sgdisk"
+URL_USERDATA="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/userdata.img"
+URL_METADATA="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/metadata.img"
 
 TARGET_BUSYBOX="$(pwd)/busybox"
 TARGET_MKFS_FAT="$(pwd)/mkfs.fat"
@@ -16,6 +18,8 @@ TARGET_MKFS_NTFS="$(pwd)/mkfs.ntfs"
 TARGET_MOUNT_NTFS="$(pwd)/mount.ntfs"
 TARGET_PARTED="$(pwd)/parted"
 TARGET_SGDISK="$(pwd)/sgdisk"
+TARGET_USERDATA="$(pwd)/userdata.img"
+TARGET_METADATA="$(pwd)/metadata.img"
 
 
 # Check the device codename using getprop
@@ -67,6 +71,8 @@ download_and_set_permissions "$URL_MKFS_NTFS" "$TARGET_MKFS_NTFS"
 download_and_set_permissions "$URL_MOUNT_NTFS" "$TARGET_MOUNT_NTFS"
 download_and_set_permissions "$URL_PARTED" "$TARGET_PARTED"
 download_and_set_permissions "$URL_SGDISK" "$TARGET_SGDISK"
+download_and_set_permissions "$URL_USERDATA" "$TARGET_USERDATA"
+download_and_set_permissions "$URL_METADATA" "$TARGET_METADATA"
 echo ""
 echo ""
 echo "All binaries have been downloaded and permissions set."
@@ -74,9 +80,9 @@ echo ""
 echo ""
 
 
-#!/sbin/bash
 win=/dev/block/sda32
 esp=/dev/block/sda33
+
 removeparts(){ for i in 33 32 31; do $(pwd)/parted -s /dev/block/sda rm $i 2>/dev/null; done }
 
 formatwinesp(){
@@ -84,12 +90,10 @@ $(pwd)/mkfs.fat -F32 -s1 $esp -n ESPNABU
 $(pwd)/mkfs.ntfs -f $win -L WINNABU
 }
 
-
-[ "$ignoreweirdness" != true ] && for i in 1 2 3 4; do test -e /dev/block/by-name/bk0$i || {
-    echo "this script will NOT work with weird partition layouts! please restore the partition table by flashing gpt_both0 in fastboot!"
-    exit 1
-}; done
-
+formatandroid(){
+$(pwd)/busybox dd if=$(pwd)/userdata.img of=/dev/block/sda31
+$(pwd)/busybox dd if=$(pwd)/metadata.img of=/dev/block/sda19
+}
 
 blocksize=$($(pwd)/busybox blockdev --getsize64 /dev/block/sda)
 if [[ $blocksize =~ ^125[0-9]{9}$ ]]; then max=125586
@@ -98,32 +102,30 @@ elif [[ $blocksize =~ ^509[0-9]{9}$ ]]; then max=509465
 else echo "is this nabu?"; exit 1
 fi
 
-if [ "$ignoreweirdness" != true ]; then
-    weirdparts=$(find /dev/block -regextype posix-extended -type b -regex '.*/sda(3[4-9]|[4-9][0-9])$')
-    if [ -n "$weirdparts" ]; then
-        echo -n "in order to use this script, your partition table has to be restored to the stock variant. ALL DATA WILL BE LOST. continue (y/n)? "
-        read yn
-        [[ $yn =~ ^[Yy].*$ ]] || {
-            echo "can't proceed without restoring the table."
-            exit 1
-        }
-        echo "restoring the stock partition layout now"
-        for i in $weirdparts; do
-            f="${i:14}"
-            parted -s /dev/block/sda rm $f 2>/dev/null
-        done
-        restore
-        exit 0
-    fi
-fi
-
-
-if [[ -n $1 ]]; then
+echo "Do you want to proceed with partitioning? (y/n)"
+read -r first_confirmation
+    if [[ "$first_confirmation" == "y" || "$first_confirmation" == "yes" ]]; then
+        echo "Warning: All data will be erased. Do you want to continue? (y/n)"
+        read -r second_confirmation
+        if [[ "$second_confirmation" != "y" && "$second_confirmation" != "yes" ]]; then
+            echo "Repartitioning cancelled."
+            exit
+        fi
+        
+        while true; do
+        # Prompt the user for the Windows partition size
+        echo "Enter the size for the Windows partition in GB:"
+        read -r size_win
+        if ! [[ $size_win =~ ^[0-9]+$ ]]; then
+            echo "Invalid size. Please enter a number."
+            continue
+        fi
+if [[ -n $size_win ]]; then
 winmax=$(echo "($max - 10872 - 400 - 100)/1000" | bc)
 echo "min size is 20, max size is less then $winmax"
-! [[ -z $2 && $1 =~ ^[0-9]{1,3}(\.[0-9])?$ && $(echo "20 < $1 && $1 < $winmax" | bc) == 1 ]] && echo "invalid argument!" && exit 1
-echo ""$(echo "scale=2; $1*1000/1024" | bc)"GiB of space will be given to the main windows parition"
-userdataend=$(echo "$max - $1*1000 - 400" | bc)
+! [[ -z $2 && $size_win =~ ^[0-9]{1,3}(\.[0-9])?$ && $(echo "20 < $size_win && $size_win < $winmax" | bc) == 1 ]] && echo "invalid argument!" && exit 1
+echo ""$(echo "scale=2; $size_win*1000/1024" | bc)"GiB of space will be given to the main windows parition"
+userdataend=$(echo "$max - $size_win*1000 - 400" | bc)
 echo "userdata will get "$(echo "scale=2;($userdataend-10872)/1024" | bc)"GiB of space"
 echo -n "does that sound good (y/n)? "
 read yn
@@ -139,4 +141,16 @@ $(pwd)/parted -s /dev/block/sda \
   set 33 esp on
 sync
 formatwinesp
+formatandroid
 echo "done!"
+echo "Repartitioning completed."
+echo ""
+echo "NOW YOUR DEVICE BOOT TO RECOVERY. THEN WIPE DATA THERE,"
+echo "then reboot. AND COMPLETE SETUP EVERYTHING"
+echo "INSTALL MAGISK AND THEN CONTINUE TO RE-RUN EVERYTHING"
+echo ""
+echo "Repartitioning done! Press any key to reboot..."
+read -n 1 -s key  # Wait for a key press
+echo "Waiting for 5 seconds before rebooting..."
+sleep 5
+reboot
