Update testlib

diff --git a/testlib b/testlib
--- a/testlib
+++ b/testlib
@@ -28,7 +28,7 @@ TARGET_WIMLIB="$(pwd)/wimlib-imagex"
 DEVICE_CODENAME=$(getprop ro.product.device)
 
 if [ "$DEVICE_CODENAME" = "nabu" ]; then
-    echo "test-16"
+    echo "test-17"
     echo "WinInstaller for Xiaomi Pad 5 ($DEVICE_CODENAME)"
     echo "this script is Written and Made By ArKT, Telegram - '@ArKT_7', Github - 'ArKT-7'"
     echo ""
@@ -93,6 +93,9 @@ TARGET_FILE2="$(pwd)/userdata.img"
 # URL3="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/metadata.img"
 # TARGET_FILE3="$(pwd)/metadata.img"
 
+URL4="https://raw.githubusercontent.com/arkt-7/NoPcWinstall/main/bin/install.bat"
+TARGET_FILE4="$(pwd)/install.bat"
+
 # Download the Toolbox.zip file
 echo "Downloading additional Windows tools file (Toolbox.zip), office, activator, and other things"
 $(pwd)/busybox wget -O "$TARGET_FILE1" "$URL1"
@@ -114,6 +117,18 @@ if [ $? -eq 0 ]; then
     echo "Download complete for userdata.img."
 else
     echo "Failed to download $URL2."
+    exit 1
+fi
+
+# Download the install.bat file
+echo "Downloading install.bat"
+$(pwd)/busybox wget -O "$TARGET_FILE4" "$URL4"
+
+# Check if the download was successful
+if [ $? -eq 0 ]; then
+    echo "Download complete for install.bat."
+else
+    echo "Failed to download $URL4."
     exit 1
 fi
 
@@ -582,7 +597,7 @@ echo "Copying files..."
 $(pwd)/busybox mkdir -p /mnt/win/installer/Driver
 $(pwd)/busybox mkdir -p /mnt/win/importantbackups
 copy_with_progress /sdcard/nopcwinstall/uefi.img /sdcard/UEFI/uefi.img
-copy_with_progress /sdcard/nopcwinstall/install.bat /mnt/win/installer/install.bat
+copy_with_progress $(pwd)/install.bat /mnt/win/installer/install.bat
 copy_with_progress /sdcard/importantbackups/boot.img /mnt/win/boot.img
 echo "Copying Important .img Backup files just in case if needed further..."
 $(pwd)/busybox cp -r /sdcard/importantbackups/* /mnt/win/importantbackups/
