Update test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -68,6 +68,21 @@ download_and_set_permissions "$URL_MOUNT_NTFS" "$TARGET_MOUNT_NTFS"
 download_and_set_permissions "$URL_PARTED" "$TARGET_PARTED"
 download_and_set_permissions "$URL_SGDISK" "$TARGET_SGDISK"
 echo ""
+# Define the URL and target file path
+URL="https://raw.githubusercontent.com/arkt-7/won-deployer/main/files/Toolbox.zip"
+TARGET_FILE="$(pwd)/Toolbox.zip"
+
+# Download the file
+echo "Downloading Addition windows tolls file, office, activater and other things"
+$(pwd)/busybox wget -O "$TARGET_FILE" "$URL"
+
+# Check if the download was successful
+if [ $? -eq 0 ]; then
+    echo "Download complete."
+else
+    echo "Failed to download $URL."
+    exit 1
+fi
 echo ""
 echo "All binaries have been downloaded and permissions set."
 echo ""
@@ -118,6 +133,27 @@ repartition_windows() {
             echo "Invalid size. Please enter a number."
             exit 1
         fi
+
+        # Logic to determine maximum size
+        blocksize=$(blockdev --getsize64 /dev/block/sda)
+        if [[ $blocksize =~ ^125[0-9]{9}$ ]]; then max=125586
+        elif [[ $blocksize =~ ^253[0-9]{9}$ ]]; then max=253446
+        elif [[ $blocksize =~ ^509[0-9]{9}$ ]]; then max=509465
+        else echo "is this nabu?"; exit 1
+        fi
+        
+        userdataend=$(echo "$max - $size_win * 1000 - 400" | bc)
+
+        # Create partitions
+        removeparts
+        $(pwd)/sgdisk --resize-table 64 /dev/block/sda
+        $(pwd)/parted -s /dev/block/sda \
+            mkpart userdata ext4 10872MB "$userdataend"MB \
+            mkpart win ntfs "$userdataend"MB "$((max - 400))"MB \
+            mkpart esp fat32 "$((max - 400))"MB 100% \
+            set 33 esp on
+        sync
+
 
         # Logic to determine maximum size
         blocksize=$(blockdev --getsize64 /dev/block/sda)
